# Generated by Django 4.1 on 2022-09-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_rename_catalogo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='Edad',
            field=models.CharField(default='', max_length=5),
        ),
    ]
