# Generated by Django 4.1 on 2022-09-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='description',
        ),
        migrations.AddField(
            model_name='owner',
            name='Pais',
            field=models.CharField(default='', max_length=30),
        ),
    ]
