# Generated by Django 4.1 on 2022-09-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_remove_owner_description_owner_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='Pais',
            new_name='pais',
        ),
    ]
