# Generated by Django 4.0.6 on 2022-08-28 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='dia_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 17, 56, 3, 4864, tzinfo=utc)),
        ),
    ]
