# Generated by Django 4.0.6 on 2022-08-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalogo_dia_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogo',
            name='dia_creacion',
        ),
    ]
